// GENERATED by shruggie-brandbuilder.
export function OpenGraphImage({ className }: { className?: string }) {
  return (
    <img
      className={className}
      src="/cueson-social-preview-1280.png"
      alt="Cueson, Universal subtitle and caption interchange"
    />
  )
}
