package conformance_test

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/shruggietech/cueson/internal/cli"
	"github.com/shruggietech/cueson/internal/codec/scripted"
	"github.com/shruggietech/cueson/internal/model"
	"github.com/shruggietech/cueson/internal/schema"
	"github.com/shruggietech/cueson/internal/source"
	"github.com/shruggietech/cueson/internal/testutil"
)

// These compact expectations are authored from the selected profile, not
// generated by the parser. Native capture, common projection and diagnostics
// have independent comparisons; source bytes remain their own restore oracle.
type scriptedExpectation struct {
	Format          string                  `json:"format"`
	SectionNames    []string                `json:"section_names"`
	RecordCount     int                     `json:"record_count"`
	Styles          []scriptedStyleExpected `json:"styles"`
	Events          []scriptedEventExpected `json:"events"`
	AttachmentNames []string                `json:"attachment_names"`
	Cues            []scriptedCueExpected   `json:"cues"`
	RenderResult    string                  `json:"render_result"`
}

type scriptedFieldExpected struct {
	FieldName string `json:"field_name"`
	RawValue  string `json:"raw_value"`
}
type scriptedStyleExpected struct {
	Name   string                  `json:"name"`
	Fields []scriptedFieldExpected `json:"fields"`
}
type scriptedEventExpected struct {
	EventType string                  `json:"event_type"`
	Fields    []scriptedFieldExpected `json:"fields"`
}
type scriptedCueExpected struct {
	StartMilliseconds int64           `json:"start_milliseconds"`
	EndMilliseconds   int64           `json:"end_milliseconds"`
	RawText           string          `json:"raw_text"`
	PlainText         string          `json:"plain_text"`
	Lines             []string        `json:"lines"`
	Speakers          []model.Speaker `json:"speakers"`
	Tokens            []model.Token   `json:"tokens"`
	DrawingExcluded   bool            `json:"drawing_excluded"`
}
type scriptedDiagnosticExpected struct {
	Severity    string `json:"severity"`
	Code        string `json:"code"`
	SourceOrder int    `json:"source_order"`
}

func TestScriptedGovernedIngestRenderRestoreConformance(t *testing.T) {
	t.Parallel()
	root := fixtureRoot(t)
	manifest := verifiedManifest(t, root)
	accepted := 0
	for _, fixture := range manifest.Fixtures {
		if !strings.HasPrefix(fixture.ID, "scripted/") || fixture.Expectation.Result != "accepted" {
			continue
		}
		accepted++
		t.Run(fixture.ID, func(t *testing.T) {
			t.Parallel()
			original := readArtifact(t, root, mustArtifact(t, fixture, "source"))
			var want scriptedExpectation
			decodeScriptedExpected(t, readArtifact(t, root, mustArtifact(t, fixture, "expected_model")), &want)
			parsed, err := scripted.Parse(context.Background(), original, want.Format)
			if err != nil {
				t.Fatalf("accepted native parse: %v", err)
			}
			assertScriptedProjection(t, want, parsed.Native, parsed.Cues)
			assertScriptedPhysicalCapture(t, original, parsed.Native)
			var diagnostics []scriptedDiagnosticExpected
			decodeScriptedExpected(t, readArtifact(t, root, mustArtifact(t, fixture, "expected_diagnostics")), &diagnostics)
			if got := scriptedDiagnostics(parsed.Diagnostics); !reflect.DeepEqual(got, diagnostics) {
				t.Fatalf("ordered diagnostics = %#v, want %#v", got, diagnostics)
			}
			document, encoded := encodeScriptedFixture(t, root, fixture)
			native := document.FormatData.ASS
			if want.Format == "ssa" {
				native = document.FormatData.SSA
			}
			if native == nil {
				t.Fatal("encoded document omitted the matching native branch")
			}
			assertScriptedProjection(t, want, *native, document.Cues)
			if got := scriptedDiagnostics(document.Diagnostics); !reflect.DeepEqual(got, diagnostics) {
				t.Fatalf("encoded ordered diagnostics = %#v, want %#v", got, diagnostics)
			}
			if err = source.ValidateIntegrity(context.Background(), document); err != nil {
				t.Fatal(err)
			}
			asset := document.Source.Assets[0]
			captured, err := base64.StdEncoding.Strict().DecodeString(asset.DataBase64)
			if err != nil || !bytes.Equal(captured, original) {
				t.Fatal("source envelope changed accepted original bytes")
			}
			originalArtifact := mustArtifact(t, fixture, "source")
			if err = testutil.CompareIntegrity(fixture.ID, "captured_source", captured, *originalArtifact.SizeBytes, originalArtifact.SHA256); err != nil {
				t.Fatal(err)
			}
			output := filepath.Join(t.TempDir(), "restored."+want.Format)
			if _, err = source.Restore(context.Background(), document, source.RestoreOptions{Output: output}); err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(readFile(t, output), original) {
				t.Fatal("exact restoration changed original source bytes")
			}
			if !bytes.Equal(readArtifact(t, root, originalArtifact), original) {
				t.Fatal("verification mutated original fixture")
			}
			if err = testutil.CheckNoForbidden(fixture.ID, "encoded_document", encoded, root, testutil.ArtifactFile(root, originalArtifact), filepath.Dir(output)); err != nil {
				t.Fatal(err)
			}
			rendered, err := scripted.Render(context.Background(), document, false)
			if want.RenderResult == "rejected" {
				if err == nil || len(rendered.Bytes) != 0 {
					t.Fatalf("unrenderable retained content published output: %v", err)
				}
				return
			}
			if err != nil {
				t.Fatalf("permissive model rendering: %v", err)
			}
			if expected, ok := fixture.ArtifactByID("expected_bytes"); ok {
				if err = testutil.CompareBytes(fixture.ID, "authored_render_bytes", readArtifact(t, root, expected), rendered.Bytes); err != nil {
					t.Fatal(err)
				}
			}
			if bytes.HasPrefix(rendered.Bytes, []byte{0xef, 0xbb, 0xbf}) || bytes.ContainsRune(rendered.Bytes, '\r') || !bytes.HasSuffix(rendered.Bytes, []byte{'\n'}) {
				t.Fatal("render output violated UTF-8/no-BOM/LF/final-LF profile")
			}
			again, err := scripted.Render(context.Background(), document, false)
			if err != nil || !bytes.Equal(rendered.Bytes, again.Bytes) {
				t.Fatal("repeated rendering is not deterministic")
			}
			reparsed, err := scripted.Parse(context.Background(), rendered.Bytes, want.Format)
			if err != nil {
				t.Fatalf("renderer emitted unparsable native content: %v", err)
			}
			assertScriptedSemanticCycle(t, parsed, reparsed)
			strict, strictErr := scripted.Render(context.Background(), document, true)
			if len(diagnostics) > 0 && (strictErr == nil || len(strict.Bytes) != 0) {
				t.Fatal("strict rendering published diagnosed ambiguity")
			}
			if len(diagnostics) == 0 && strictErr != nil {
				t.Fatalf("strict rendering rejected clean corpus: %v", strictErr)
			}
		})
	}
	if accepted < 20 {
		t.Fatalf("scripted accepted fixture count = %d, want paired native coverage", accepted)
	}
}

func TestScriptedGovernedMalformedAtomicPrivacyConformance(t *testing.T) {
	t.Parallel()
	root := fixtureRoot(t)
	manifest := verifiedManifest(t, root)
	rejected := 0
	for _, fixture := range manifest.Fixtures {
		if !strings.HasPrefix(fixture.ID, "scripted/") || fixture.Expectation.Result != "rejected" {
			continue
		}
		rejected++
		t.Run(fixture.ID, func(t *testing.T) {
			t.Parallel()
			input := mustArtifact(t, fixture, "input")
			original := readArtifact(t, root, input)
			format := strings.TrimPrefix(fixture.ID, "scripted/")[:3]
			parsed, err := scripted.Parse(context.Background(), original, format)
			if err == nil || !strings.Contains(err.Error(), *fixture.Expectation.DiagnosticContains) {
				t.Fatalf("rejection = %v, want %q", err, *fixture.Expectation.DiagnosticContains)
			}
			if len(parsed.Cues) != 0 || len(parsed.Native.Records) != 0 {
				t.Fatal("fatal parse published a partial native model")
			}
			directory := t.TempDir()
			path := filepath.Join(directory, "rejected."+format)
			if err = os.WriteFile(path, original, 0o600); err != nil {
				t.Fatal(err)
			}
			var stdout, stderr bytes.Buffer
			status := cli.Run(context.Background(), []string{"encode", "--stdout", path}, strings.NewReader(""), &stdout, &stderr)
			if status == cli.ExitSuccess || stdout.Len() != 0 {
				t.Fatalf("fatal CLI encode published output: status %d, stdout bytes %d", status, stdout.Len())
			}
			if !bytes.Equal(readFile(t, path), original) {
				t.Fatal("fatal encode changed its source")
			}
			entries, err := os.ReadDir(directory)
			if err != nil || len(entries) != 1 {
				t.Fatal("fatal encode created destination artifacts")
			}
			if err = testutil.CheckNoForbidden(fixture.ID, "fatal_diagnostics", stderr.Bytes(), root, directory, path, "assets/movie.mp4", `C:\private\video.mp4`); err != nil {
				t.Fatal(err)
			}
		})
	}
	if rejected < 40 {
		t.Fatalf("scripted rejected fixture count = %d, want paired profile/privacy coverage", rejected)
	}
}

func TestScriptedGovernedEditedOwnerRestoreIndependence(t *testing.T) {
	t.Parallel()
	root := fixtureRoot(t)
	manifest := verifiedManifest(t, root)
	for _, format := range []string{"ass", "ssa"} {
		t.Run(format, func(t *testing.T) {
			t.Parallel()
			fixture := mustFixture(t, manifest, "scripted/"+format+"-basic")
			original := readArtifact(t, root, mustArtifact(t, fixture, "source"))
			document, _ := encodeScriptedFixture(t, root, fixture)
			native := document.FormatData.ASS
			if format == "ssa" {
				native = document.FormatData.SSA
			}
			cue := &document.Cues[0]
			cue.Timing = model.Timing{StartMilliseconds: 5000, EndMilliseconds: 7000, DurationMilliseconds: 2000}
			start, end, span := int64(5000), int64(7000), int64(2000)
			document.Document.MediaStartMilliseconds = &start
			document.Document.MediaEndMilliseconds = &end
			document.Document.MediaSpanMilliseconds = &span
			document.Stats.MediaSpanMilliseconds = &span
			text := `Edited, native\Ntext`
			event := &native.Events[0]
			event.Text = text
			for i := range event.Fields {
				identity, known := model.ScriptedFieldIdentity(event.Fields[i].FieldName, format, "event")
				if known && identity == "text" {
					event.Fields[i].RawValue = text
					if event.Fields[i].TypedValue != nil {
						event.Fields[i].TypedValue.String = &text
					}
				}
			}
			facts, err := model.ProjectScriptedText(text, 0, start, end)
			if err != nil {
				t.Fatal(err)
			}
			event.Spans, event.Tags, event.Karaoke = facts.Spans, facts.Tags, facts.Karaoke
			cue.Payload = model.Payload{RawText: text, PlainText: "Edited, native\ntext", Lines: []string{"Edited, native", "text"}}
			cue.Tokens = facts.Tokens
			if err = document.Validate(); err != nil {
				t.Fatalf("legal owning edits invalidated truthful original captures: %v", err)
			}
			rendered, err := scripted.Render(context.Background(), document, true)
			if err != nil {
				t.Fatal(err)
			}
			parsed, err := scripted.Parse(context.Background(), rendered.Bytes, format)
			if err != nil {
				t.Fatal(err)
			}
			if len(parsed.Cues) != 1 || parsed.Cues[0].Timing.StartMilliseconds != start || parsed.Cues[0].Timing.EndMilliseconds != end || parsed.Cues[0].Payload.RawText != text {
				t.Fatal("rendering replayed stale raw source instead of owning edits")
			}
			output := filepath.Join(t.TempDir(), "original."+format)
			if _, err = source.Restore(context.Background(), document, source.RestoreOptions{Output: output}); err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(readFile(t, output), original) || bytes.Equal(rendered.Bytes, original) {
				t.Fatal("model-driven edited rendering and original-byte restoration were conflated")
			}
		})
	}
}

func decodeScriptedExpected(t *testing.T, data []byte, value any) {
	t.Helper()
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(value); err != nil {
		t.Fatal(err)
	}
}

func scriptedFields(fields []model.ScriptedField) []scriptedFieldExpected {
	result := make([]scriptedFieldExpected, 0, len(fields))
	for _, field := range fields {
		result = append(result, scriptedFieldExpected{FieldName: strings.Trim(field.FieldName, " "), RawValue: field.RawValue})
	}
	return result
}

func assertScriptedProjection(t *testing.T, want scriptedExpectation, native model.ScriptedDocumentData, cues []model.Cue) {
	t.Helper()
	got := scriptedExpectation{Format: want.Format, SectionNames: []string{}, RecordCount: len(native.Records), Styles: []scriptedStyleExpected{}, Events: []scriptedEventExpected{}, AttachmentNames: []string{}, Cues: []scriptedCueExpected{}, RenderResult: want.RenderResult}
	for _, section := range native.Sections {
		got.SectionNames = append(got.SectionNames, section.Name)
	}
	for _, style := range native.Styles {
		got.Styles = append(got.Styles, scriptedStyleExpected{Name: style.Name, Fields: scriptedFields(style.Fields)})
	}
	for _, event := range native.Events {
		got.Events = append(got.Events, scriptedEventExpected{EventType: event.EventType, Fields: scriptedFields(event.Fields)})
	}
	for _, attachment := range native.Attachments {
		got.AttachmentNames = append(got.AttachmentNames, attachment.Name)
	}
	for _, cue := range cues {
		nativeCue := cue.FormatData.ASS
		if want.Format == "ssa" {
			nativeCue = cue.FormatData.SSA
		}
		if nativeCue == nil {
			t.Fatal("cue omitted native projection provenance")
		}
		got.Cues = append(got.Cues, scriptedCueExpected{StartMilliseconds: cue.Timing.StartMilliseconds, EndMilliseconds: cue.Timing.EndMilliseconds, RawText: cue.Payload.RawText, PlainText: cue.Payload.PlainText, Lines: cue.Payload.Lines, Speakers: cue.Speakers, Tokens: cue.Tokens, DrawingExcluded: nativeCue.Projection.DrawingExcluded})
	}
	if !reflect.DeepEqual(got, want) {
		g, _ := json.MarshalIndent(got, "", "  ")
		w, _ := json.MarshalIndent(want, "", "  ")
		t.Fatalf("independent authored projection mismatch\ngot %s\nwant %s", g, w)
	}
}

func scriptedDiagnostics(diagnostics []model.Diagnostic) []scriptedDiagnosticExpected {
	result := make([]scriptedDiagnosticExpected, 0, len(diagnostics))
	for _, diagnostic := range diagnostics {
		order := -1
		if diagnostic.SourceOrder != nil {
			order = *diagnostic.SourceOrder
		}
		result = append(result, scriptedDiagnosticExpected{Severity: diagnostic.Severity, Code: diagnostic.Code, SourceOrder: order})
	}
	return result
}

func assertScriptedPhysicalCapture(t *testing.T, original []byte, native model.ScriptedDocumentData) {
	t.Helper()
	decoded := strings.TrimPrefix(string(original), "\ufeff")
	decoded = strings.ReplaceAll(decoded, "\r\n", "\n")
	lines := strings.Split(strings.TrimSuffix(decoded, "\n"), "\n")
	capture := make([]*string, len(lines))
	for _, section := range native.Sections {
		if section.SourceOrder < 0 || section.SourceOrder >= len(capture) || capture[section.SourceOrder] != nil {
			t.Fatal("section capture ordering is not unique and contiguous")
		}
		capture[section.SourceOrder] = section.RawHeader
	}
	for _, record := range native.Records {
		if record.SourceOrder < 0 || record.SourceOrder >= len(capture) || capture[record.SourceOrder] != nil {
			t.Fatal("record capture ordering is not unique and contiguous")
		}
		capture[record.SourceOrder] = record.RawLine
		if record.Kind == "format_declaration" {
			_, names, ok := strings.Cut(*record.RawLine, ":")
			if !ok {
				t.Fatal("declaration lost its raw source framing")
			}
			parts := strings.Split(strings.TrimPrefix(names, " "), ",")
			if len(parts) != len(record.DeclarationFields) {
				t.Fatal("declaration occurrence count changed")
			}
			for i, part := range parts {
				if part != record.DeclarationFields[i].FieldName {
					t.Fatal("declaration field name spaces or occurrence order changed")
				}
			}
		}
	}
	for i, line := range lines {
		if capture[i] == nil || *capture[i] != line {
			t.Fatalf("physical source line %d was omitted or changed", i)
		}
	}
}

func encodeScriptedFixture(t *testing.T, root string, fixture testutil.Fixture) (model.Document, []byte) {
	t.Helper()
	path := testutil.ArtifactFile(root, mustArtifact(t, fixture, "source"))
	var stdout, stderr bytes.Buffer
	status := cli.Run(context.Background(), []string{"encode", "--stdout", path}, strings.NewReader(""), &stdout, &stderr)
	if status != cli.ExitSuccess {
		t.Fatalf("native CLI encode = %d: %s", status, stderr.Bytes())
	}
	document, err := schema.Decode(stdout.Bytes())
	if err != nil {
		t.Fatalf("encoded Cue JSON failed schema/semantics: %v", err)
	}
	return document, append([]byte(nil), stdout.Bytes()...)
}

func assertScriptedSemanticCycle(t *testing.T, first, second scripted.ParseResult) {
	t.Helper()
	// IDs and SourceOrder are stable for captured declarations in this corpus.
	// Capture-only raw views and canonical recognized scalar lexemes are excluded;
	// unknown values, declaration spelling/order and all native Text remain exact.
	normalize := func(parsed scripted.ParseResult) string {
		data, _ := json.Marshal(parsed.Native)
		var native model.ScriptedDocumentData
		_ = json.Unmarshal(data, &native)
		for i := range native.Sections {
			native.Sections[i].RawHeader = nil
		}
		for i := range native.Records {
			if native.Records[i].Kind != "unknown" && native.Records[i].Kind != "comment" && native.Records[i].Kind != "blank" && native.Records[i].Kind != "attachment_data" {
				native.Records[i].RawLine = nil
			}
		}
		for i := range native.Styles {
			for j := range native.Styles[i].Fields {
				f := &native.Styles[i].Fields[j]
				if f.TypedValue != nil {
					// The typed value itself owns equality.
					f.RawValue = ""
				}
			}
		}
		for i := range native.Events {
			for j := range native.Events[i].Fields {
				f := &native.Events[i].Fields[j]
				if f.TypedValue != nil && f.TypedValue.Kind != "string" {
					f.RawValue = ""
				}
			}
		}
		encoded, _ := json.Marshal(struct {
			Native model.ScriptedDocumentData `json:"native"`
			Cues   []model.Cue                `json:"cues"`
		}{Native: native, Cues: parsed.Cues})
		return string(encoded)
	}
	if got, want := normalize(second), normalize(first); got != want {
		t.Fatalf("native semantic/retention cycle changed\nfirst %s\nsecond %s", want, got)
	}
}
